### ISSUE TITLE
Crash on NPE

### ISSUE THREAD

**Issue by haluzpav** [humansis/offline_app#4]
Only on some devices.

```
  "REPORT_ID": "c1e57cd2-9eaa-45a5-8c8b-dc7406dfbe9e",
  "APP_VERSION_CODE": 1000000,
  "APP_VERSION_NAME": "1.0.0",
  "PACKAGE_NAME": "org.humansis.app.user.household.demo",
  "FILE_PATH": "\/data\/user\/0\/org.humansis.app.user.household.demo\/files",
  "PHONE_MODEL": "ONEPLUS A5010",
  "BRAND": "OnePlus",
  "PRODUCT": "OnePlus5T",
  "ANDROID_VERSION": "9",
```

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int cz.applifting.humansis.model.db.BeneficiaryLocal.getBeneficiaryId()' on a null object reference
	at cz.applifting.humansis.repositories.BeneficiariesRepository.isAssignedInOtherDistribution(BeneficiariesRepository.kt:101)
	at cz.applifting.humansis.ui.main.distribute.beneficiary.BeneficiaryViewModel$initBeneficiary$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:136)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:33)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(CoroutinesRoom.kt:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by haluzpav** [comment]
Also happens while in background.

**Comment by haluzpav** [comment]
Fixed. It was probably happening when beneficiary detail was open and sync was started automatically.
